### ISSUE TITLE
Request: Share the hyper-parameters found in the grid search

### ISSUE THREAD

**Issue by jotaf98** [abahde/DeepOBS#17]
To lessen the burden of re-running the benchmark, would it be possible to publish the optimal hyper-parameters somewhere?

By-reusing those hyper-parameters, one would avoid the most computationally-demanding part of reproducing the results (by 1-2 orders of magnitude).

**Comment by fsschneider** [comment]
You can find all our results here: https://github.com/fsschneider/DeepOBS_Baselines

The used hyperparameters are both written in the `.json` file itself as well as in the path name.
The optimal hyperparameter we found are the ones that have 10 log files for a single setting (they are using different seeds in order to report a variance estimate of the results).

But I do realize that this is not the best way to present them. We have a new release planned with much better baselines. We will also work on making them more accessible.

---
The paper also has the optimal hyperparameters listed. Check out Table 2 of https://arxiv.org/pdf/1903.05499.pdf

You could also use the `get_best_run` function of the analyzer here: https://github.com/fsschneider/DeepOBS/blob/master/deepobs/analyzer/analyze.py#L18 once you downloaded the baselines.

**Comment by jotaf98** [comment]
Thanks for the tips, `get_best_run` seems to illustrate the best way to get them then.

Also, I don't know how I missed that in Table 2, should've been obvious!
